name: Java Ant Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Ant
      run: sudo apt-get install ant

    - name: Compile project
      run: ant compile

    - name: Add JAR library
      run: cp jexer-1.6.0.jar lib/

    - name: Create JAR with library
      run: ant -lib lib/jexer-1.6.0.jar jar
